import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const inter = Inter({ subsets: ['latin'] })

const stardust = localFont({
  src: [
    {
      path: "../font/stardust.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../font/stardust-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" className={`${stardust.className}`}>
      <body>{children}</body>
    </html>
  );
}
